<div align="center">

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.png)](https://colab.research.google.com/github/wisaaco/Curs_FG24GOI0074221/blob/main/lessons/2_Python_Introduccio.ipynb)

Si no funciona el botó podeu copiar el següent [enllaç](https://colab.research.google.com/github/wisaaco/Curs_FG24GOI0074221/blob/main/lessons/2_Python_Introduccio.ipynb)

</div>

# Unitat 3: Variables i estructures bàsiques de Python

Contingut de la unitat:
- Variables bàsiques
- Variables complexes
- Funcions i mètodes
- Us de llibreries
- Activitat
  

Un dels factors que influeix en la corba d'aprenentatge d'un llenguatge és la seva sintaxi. Òbviament, Python és un llenguatge més, i cal entendre la seva sintaxi.

En aquest curs veurem les principals estructures i maneres d'operar amb ella. A grans trets, el més essencial és entendre la invocació de mètodes o funcions ja definides.

Aquesta invocació es realitza amb el seu nom i parèntesis:

In [28]:
print("HOLA")

HOLA



Dins dels parèntesis, van els arguments que aquesta funció processa (separats per coma):

In [30]:
sorted([2,1,3,2,4,2],reverse=True)

[4, 3, 2, 2, 2, 1]

I podem concatenar resultats de funcions i fins i tot de variables amb l'ús d'un punt o com a argument d'una altra funció.

In [31]:
sorted([2,1,3,2,4,2],reverse=True).count(2) 

3

In [32]:
"HOLA MAR".split(" ")

['HOLA', 'MAR']

In [33]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Altres aspectes: els comentaris 

In [77]:
# Això és un comentari d'una cella amb codi. 
# Els comentaris són importants per descriure línies de codi complicades.
# Si et trobas a Colab pots executar aquesta cel·la fent: shit+enter o icona de triangle
print("Hello World !")
print("Print a list of numbers: %s"%list(range(10)))

Hello World !
Print a list of numbers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


I finalment, les assignacions

In [35]:
# Cel·la de codi #1
a = 1+1
b = 3
c = len("HOLA") #la seva longitud
d = len(["HOLA"])
print(a,b,c,d)

2 3 4 1


**Finalment, Python té una abstracció de tipus molt simple (duck typing), la qual cosa permet simplificar molt la programació i ens serà molt útil per a l'anàlisi de dades.**

In [46]:
import numpy as np # importació d'un conjunt de dades i mètodes no inclosos per defecte

valors = np.array([1,3,4,5,6])

print(valors*10)
print("-"*30)
print(valors*valors)
print("+"*30)
print(valors.mean())
print(valors.std())
print(valors.min())

[10 30 40 50 60]
------------------------------
[ 1  9 16 25 36]
++++++++++++++++++++++++++++++
3.8
1.7204650534085253
1


## Variables i operadors
Un llenguatge de programació ofereix operacions aritmètiques i lògiques relacionades amb el tipus de dades.

In [ ]:
caracter = 'a'
estring = "Hello!"
enter =  123
decimal = 1.23
complexe = 1+23j
logic = False

print(type(caracter))
print(type(estring))
print(type(enter))
print(type(decimal))
print(type(complexe))
print(type(logic))

# Pots crear totes les variables que vulguis amb format lliure.
# Intenta que les variables tinguin un nom adequat al seu contingut.
# Evita espais, símbols i accents.

nameCognoms = "Pep Vila"
telefono = "97100000"
dni = "34989542A"
pes = 80.3
pesos = [1.3, 40.3, 20.0, -1.0]

print(pesos)

En Python, els **operadors** són símbols especials que indiquen que és necessari realitzar algun tipus de computació. Els valors amb els quals actua un operador es diuen **operands**.

Ho entendrem amb un petit exemple:
```python
x = 10.0
i = 5
resultat = x + i
```
En aquest cas, l'operador `+` ens permet sumar els operands `x` i `i` junts i guardar el resultat en la variable del mateix nom. Hem de destacar que en aquest codi hem necessitat definir tres variables diferents.

Un operand pot ser una variable o literal. Definim els **literals** en un programa com la idea d'expressar un valor que no canvia en el codi font, aquests han de ser d'un dels diferents tipus de dades que hem descrit
anteriorment.

A continuació tenim un altre fragment de codi en el qual usem altres operadors i literals de tipus sencer:
```python
a = 10
b = 20
x = 45
r = (a + b - 5) + (x + 10 + 20)
```

In [ ]:
## Operadors ARITMÉTICS

a = 10
b = 20
print(a+b) # suma
print(a-b) # resta
print(-a)  # negació
print(a*b) # multiplicació
print(a/b) # divisió
print(a%b) # modul
print(a//b) # divisió entera
print(a**b) # exponent
print("---")
a = 10.3
b = 2.34

print(a%b) # modul flotant
print(a//b) # divisió entera
print(a**b) # exponent
print("---")

aj = 1+23j
bj = 23j

print(aj-bj) # resta complexe
print(-aj)  # negació complexe
print(aj*bj) # multiplicació complexe


In [ ]:
## Operadors de COMPARACIÓ
a = 10
b = 12

print(a==b) # Igualtat
print(a!=b) # diferència
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

print("---")
a = 10.0
b = 10.0
result = a==b
print(result)

In [ ]:
## Operadors lògics
a = 10.0
b = 10.0
c = True
f = False
print(not(a==b))
print(c or f)
print(c and (a==c))
print(True and True)
print(False or True)
print(not(not(not(True))))

In [ ]:
# Print data
a = "HOLA"
b = 10
c = 3.141618

print("This is the value of a string %s"%a)
print("This is the value of a integer %i"%b)
print("This is the value of a float %f"%c)
print("This is the value of a float %0.2f"%c)

print("---")
print("Print a float as a integer %i"%c)
print("Print a integer as a string %s"%b)

print("---")
print("Print a string as a float %f"%a) # ERRORs!

#### Activitat


Suposem que un objecte es llança verticalment cap amunt des del sòl amb una velocitat inicial de 20 m/s. L'acceleració deguda a la gravetat és de -9.8 m/s². Calcula:

a) El temps que trigarà a aconseguir la seva altura màxima.

Formula:
v = o + a * t

On:
- v = velocitat final
- o = velocitat inicial
- a = acceleració
- t = temps


In [ ]:
v = 0
a = -9.8


b) L'altura màxima que aconseguirà l'objecte.

Formula: <br/>

s = ot + (1/2) * a * t²

On:
- s = desplaçament vertical (altura)
- o = velocitat inicial
- a = acceleració
- t = temps

## Operacions de control

No volem introduir molta complexitat en aquest curs, però has d'entendre que podem fer certes operacions de control amb les dades: recorreguts de seqüències, comprovacions, etc.

In [ ]:
name = "Pep"
grau = 0.3

if name == "Pep":
    factor = 10
else: 
    factor = 1

grau = grau * factor
print("Grau d'amistat amb %s es: %f "%(name,grau))

In [ ]:
names = ["Pep","Lluis","Paco"]

for name in names:
    grau = 0.3

    if name == "Pep":
        factor = 10
    else: 
        factor = 1

    grau = grau * factor
    print("Grau d'amistat amb %s es: %f "%(name,grau))

In [ ]:
names = ["Pep","Lluis","Paco"]

i = 0
while i<len(names):
    print(names[i])
    i+=1

#### Activitat
Donada aquesta llista de noms es demana:

In [ ]:
noms = ["Ruscalleda", "Nadal", "Gaudi", "Rodoreda"]

In [ ]:
# 1. Està "Gasol" en aquesta llista: Sí/No?

In [ ]:
# 2. Imprimeix cada ítem de la llista sempre que la seva longitud (nombre de caràcters) sigui major que 6.
print(len("Paco")) #la funció len es pot aplicar a molt tipus d'objectes/variables

In [ ]:
# 3. Afegeix "Gasol" a aquesta llista

## Variables més complexes


In [ ]:
llistes =  ["Pep","Lluis","Paco"]  # "Corchetes"
print(llistes)
print(llistes[0])
print(len(llistes))

print("-"*20)


diccionaris = { "Pep": "324345C", "Lluis":"493094B", "Paco":"309403A"} # "Llaves"
print(diccionaris)
print(len(diccionaris))
print(diccionaris.keys())
print(diccionaris.values())
print(diccionaris["Pep"])

print("-"*20)

tuples = ("Pep",33,"3490940A") 
print(tuples)
print(tuples[1])

print("-"*20)

grups = set([0,2,2,3,"Pep","Paco","Pep"])
print(grups)
print(len(grups))
print("Paco" in grups)


És molt important conèixer el tipus de cada composició d'una variable i dels seus mètodes associats (built types)

In [ ]:
codiPostal = { "Palma": ["07004","07122"], "Inca": ["07300"]}

print(type(codiPostal))

In [ ]:
print(type(codiPostal["Palma"]))

In [ ]:
print(type(codiPostal["Palma"][0]))

In [ ]:
if "07122" in codiPostal["Palma"]:
    print("El codi 07122 és el CP de la UIB")

In [ ]:
codiPostal["Sineu"] = ["07510"]
print(codiPostal)
print(len(codiPostal))

In [ ]:
codiPostal["Sineu"].append("07511")

for key in codiPostal:
    print(key, codiPostal[key])

#### Activitat
Donat aquest objecte es demana:

In [ ]:
data = [
    {
        "nom":"Pep",
        "DNI": {
                "numero":3243434,
                "lletra":"A"
        }
    },
    {
        "nom":"Lluis",
        "DNI": {
                "numero":1000000,
                "lletra":"B"
        }
    }
]

In [ ]:
#1 . Quina lletra té el DNI de Pep.


In [ ]:
#2 . Quants elements té la variable data

In [ ]:
# 3. Afegeix una altra persona. Nota: No cal que tingui els mateix camps

## Llibreries

Python inclou moltes funcionalitats de base, però hi ha llibreries que donem molt de potencial.
Pràcticament, ja està tot implementat en Python i a les seves llibreries.

A Google Colab no cal instal·lar-ne, però a una plataforma pròpia si seria necessari. En aquest curs introductori no cobriren aquest punt.

In [ ]:
preus = [10.0, 20.3, 12.3, 13.4, 9.65, 9.98, 7.98, 9.9]

print(sum(preus)/len(preus))


In [ ]:
# Hi ha llibreries incloses en el core de Python. Estan instal·lades, però per defecte no es carreguen
import math
print(math.sqrt(preus[0])) # arrel quadrada


#### Llibreria Numpy

Numpy és la llibreria numèrica per excel·lència.

https://numpy.org/

Aquesta llibrería està instalada per defecte a Google Colab però no està a una instal·lació nativa de Python. 

In [ ]:
# Hi ha d'altres que cal instal·lar-les
import numpy as np #np és un alias

preus = [10.0, 20.3, 12.3, 13.4, 9.65, 9.98, 7.98, 9.9] # una llista de items
preus = np.array(preus) #un array/llista de valors númerics

print(preus.mean())
print(preus.std())
print(preus.min())
print(preus.max())


In [ ]:
# Operacions vectorials
preusIVA = preus*1.21
print(preusIVA)

In [ ]:
# Operacions lògiques
print(preus>10.0)
print(preus[preus>10.0])

In [ ]:
# Seleccio (slicing)
print(preus)
print(preus[3])
print(preus[-1])

print("-"*30)

print(preus[:3])
print(preus[:-1])
print(preus[2:4])
print(preus[6:])

##### <span style="color:red"> Activitat </span>

S'ha fet un petit estudi de mercat del preu d'origen de certs productes. Són preus per kilogram durant quatre dies.

L'objectiu d'aquesta activitat és la consolidació de les estructures bàsiques de Python.

In [58]:
preus = np.array(
        [ #Dia0, Dia1, Dia2, Dia3
            [30.3, 20.3, 25.9, 39.0], # Cebes, preus per cèntims/kg 
            [0.33, 0.43, 0.34, 0.12], # Patates, euro/kg
            [0.45, 0.56, 0.38, 0.43] # Taronges euro/kg
])

print(preus)

[[30.3  20.3  25.9  39.  ]
 [ 0.33  0.43  0.34  0.12]
 [ 0.45  0.56  0.38  0.43]]


Recomanacions
- Identificar quines estructures de dades tenim
- Identificar com podem seleccionar informació

**La importància del slicing**

In [49]:
preus[0] # Cebes

array([30.3, 20.3, 25.9, 39. ])

In [50]:
preus[1] # Patates

array([0.33, 0.43, 0.34, 0.12])

In [51]:
preus[2] #Taronges

array([0.45, 0.56, 0.38, 0.43])

In [66]:
preus[19]

IndexError: index 19 is out of bounds for axis 0 with size 3

In [55]:
preus[1:] #Patates i Taronges

array([[0.33, 0.43, 0.34, 0.12],
       [0.45, 0.56, 0.38, 0.43]])

In [62]:
preus[:,0] # preus del dia 0

array([0.303, 0.33 , 0.45 ])

In [65]:
preus[:,1:3] #preus del día 1 i 2

array([[0.203, 0.259],
       [0.43 , 0.34 ],
       [0.56 , 0.38 ]])

Recomanacions:
- Identifiqueu el tipus de variable i els tipus inherents que pugui tindre aquest objecte (*preuOrigin*)
- Com podem accedir a cada part?, i subapartat?

**QÜESTIONS**

In [59]:
#. 0) Preparació i normalització dels preus (resolt)

# Cebes a euro/kg. Dividir per 100
preus[0] = preus[0]/100
print(preus)

[[0.303 0.203 0.259 0.39 ]
 [0.33  0.43  0.34  0.12 ]
 [0.45  0.56  0.38  0.43 ]]


In [ ]:
# A) Quin és el preu màxim de cada producte?


In [ ]:
# B) Quin és el producte més car?

In [ ]:
# C) Quin dia són més cares les taronges?

In [ ]:
# D) I si el preu de mercat és un 20% més, quins preus tindrem?

In [ ]:
# E) Quin és el cost de comprar 3 kg de taronges i 2.5 kg de cebes el dia 2?

[![License: CC BY 4.0](https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg)](https://creativecommons.org/licenses/by/4.0/) <br/>
Isaac Lera and Gabriel Moya <br/>
Universitat de les Illes Balears <br/>
isaac.lera@uib.edu, gabriel.moya@uib.edu